import Link from "next/link";
import { BrandMark } from "@/components/BrandMark";
import { notFound } from "next/navigation";
import { setupDirectory } from "@/components/relocation-directories";
import { ReadingCarousel } from "@/components/ReadingCarousel";

export default async function SetupDetailPage({ params }: { params: Promise<{ jurisdiction: string }> }) {
  const { jurisdiction } = await params;
  const route = setupDirectory.find((item) => item.id === jurisdiction);
  if (!route) notFound();
  return <main className="min-h-screen"><Header /><section className="setup-detail-hero"><div><p className="kicker">Official setup handoff</p><h1>{route.name}</h1><p className="lead">{route.next}</p><div className="hero-actions"><Link className="primary-action" href="/move#setup">Start tracking inside my move</Link><a className="secondary-action" href={route.url} target="_blank" rel="noreferrer">Open source page</a><Link className="secondary-action" href={`/company?jurisdiction=${encodeURIComponent(route.id)}`}>Use for company move</Link></div></div><aside className="setup-glance"><h2>At a glance</h2><dl><div><dt>Authority</dt><dd>{route.authority}</dd></div><div><dt>Route</dt><dd>{route.id.toUpperCase()}</dd></div><div><dt>Status in Yala AD</dt><dd>Opened and user-reported only</dd></div></dl></aside></section><ReadingCarousel label={`${route.name} setup guide`} slides={[{ title: "Your next steps", body: <ol className="check-list"><li>Create or open a private move workspace.</li><li>Open the official source page from the workspace or this guide.</li><li>Record a reference only after the provider gives you one.</li></ol> }, { title: "What to prepare", body: <ul className="check-list">{route.prepare.map((item) => <li key={item}>{item}</li>)}</ul> }, { title: "Where to apply", body: <><p>{route.authority} owns filing, payment, booking and approval outcomes. Yala AD records only opened handoffs and user- or HR-reported references.</p><p className="form-note"><a href={route.url} target="_blank" rel="noreferrer">{route.source}</a></p></> }, { title: "Related services", body: <ul className="check-list">{route.related.map((item) => <li key={item}>{item}</li>)}</ul> }]} /><section className="plain-panel info-panel"><h2>Compare setup routes</h2><div className="setup-compare">{setupDirectory.map((item) => <Link href={`/setup/${item.id}`} key={item.id} data-active={item.id === route.id}><strong>{item.name}</strong><span>{item.authority}</span></Link>)}</div></section></main>;
}
function Header() { return <header className="topbar"><Link href="/" className="brand"><BrandMark className="brand-mark" /><span>Yala AD</span></Link><nav><Link href="/setup">Setup</Link><Link href="/company/dashboard">HR dashboard</Link><Link href="/join">Join</Link></nav></header>; }
